name = "aider"
description = "Aider (AI pair programmer)"

[setup]
commands = [
  "which aider || (which uv || pip install uv) && uv tool install --force --python python3.12 aider-chat@latest",
  "aider"
]

[keys]
optional = ["ANTHROPIC_API_KEY", "OPENAI_API_KEY"]
self_auth = false
